### ISSUE TITLE
Add details to README

### ISSUE THREAD

**Issue by gregorywong** [chingu-coders/Voyage2-Bears-24#9]
User Story:
As a user, I want to be able to learn more about this project from the README file.

Acceptance Criteria:
- [x] I can read a short summary on **why this project was built**
- [x] I can read a short summary of **what it can do**
- [x] I can read instructions on **how to install and use this**
- [x] I can find out where to view the contributor's guide and am given a **link** to `CONTRIBUTING.md`

**Comment by eddyw** [comment]
I merged "Initial Setup" into "master",
Are you working on this task?
About the third point **how to install and use this**:

1. `npm install` install all packages first

2. `npm start` executes `npm run build:dev` and `npm run start:dev`. It watches for changes in files on server code and client code. If there are changes, it reloads server or rebuilds client code

3.  `npm run build:dev` builds client code and watches for new changes

4. `npm run start:dev` starts server and watches for new changes

5. `clean:cache` was supposed to clean the cache file. Currently removes the `build` folder. Need to fix that.

You will want to use `npm start` because it runs both npm scripts in parallel.
